[ip]
name    = "jeopardy-buzz"
library = "app"
version = "0.1.0"
vendor  = "c-rus"

# To learn more about writing the manifest, see https://c-rus.github.io/orbit/4_topic/2_orbittoml.html

[dependencies]
crus.util.toolbox = "0.1"